name: fin_app_ui
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  carousel_slider: ^4.1.1
  font_awesome_flutter: ^10.1.0
  date_time_picker: ^2.1.0





dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  assets:
    - assets/pics/
    - assets/icons/
    - assets/logos/

  uses-material-design: true

